development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: apollo_development
  pool:     5
  username: apollo
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: apollo_test
  pool:     5
  username: apollo
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: apollo_production
  pool:     5
  username: apollo
  password:
  template: template0